CREATE TABLE "HR"."NOTICE" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"WRITEDATE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEW_COUNT" NUMBER(38,0)
   )
   
   --추천게시판(RECOMMEND)
   --re_no 숫자
   --title, content, writer 문자
   
   CREATE TABLE RECOMMEND (
   RE_NO NUMBER(38,0),
   TITLE VARCHAR2(100),
   CONTENT VARCHAR2(100),
   WRITER VARCHAR2(100)
   
   )
   
   DROP TABLE RECOMMEND --테이블 통째로 버림
   
 CREATE TABLE RECOMMEND (
   RE_NO NUMBER(38,0),
   TITLE VARCHAR2(100),
   CONTENT VARCHAR2(100),
   WRITER VARCHAR2(100)
   
   )
   
    CREATE TABLE RECOMMEND (
   RE_NO NUMBER(38,0),
   TITLE VARCHAR2(100),
   CONTENT VARCHAR2(100),
   WRITER VARCHAR2(100)
   
   )
   
 DROP TABLE RECOMMEND --테이블 통째로 버림
   
 CREATE TABLE RECOMMEND (
   RE_NO NUMBER(38,0),
   TITLE VARCHAR2(100),
   CONTENT VARCHAR2(100),
   WRITER VARCHAR2(100)
   
   )
   
    CREATE TABLE RECOMMEND (
   RE_NO NUMBER(38,0),
   TITLE VARCHAR2(100),
   CONTENT VARCHAR2(100),
   WRITER VARCHAR2(100)
   
   )
   
   ALTER TABLE HR.RECOMMEND MODIFY CONTENT VARCHAR2(333)
   
   ALTER TABLE HR.RECOMMEND ADD VIEW_COUNT NUMBER(38,0)
   
   ALTER TABLE RECOMMEND DROP COLUMN VIEW_COUNT;
   
  
  CREATE TABLE "HR"."BOARD3" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"WRITEDATE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEW_COUNT" NUMBER(38,0)
   )
   
ALTER TABLE BOARD3 MODIFY WRITER VARCHAR2 (200)

ALTER TABLE BOARD3 DROP COLUMN VIEW_COUNT

ALTER TABLE BOARD3 ADD TES VARCHAR2 (100)


CREATE USER apple IDENTIFIED BY a1234

GRANT CONNECT, resource, dba TO apple


CREATE TABLE PROUCT222 (
	ID VARCHAR2(100),
	NAME VARCHAR2(100),
	CONTENT VARCHAR2(100),
	PRICE NUMBER(38,0)
)

INSERT INTO MEMBER VALUES ('100','100','park','011')

INSERT INTO MEMBER VALUES ('200','200','park','011')

INSERT INTO MEMBER VALUES ('300','100','park','011')

SELECT * FROM MEMBER

SELECT * FROM MEMBER WHERE ID = '100'   -- 아이디가 100인 모든 컬럼

SELECT ID FROM MEMBER WHERE ID = '100'  -- ID가 100인 ID 컬럼

SELECT ID, NAME FROM MEMBER WHERE ID = '100'  -- ID가 100인 ID, NAME 컬럼

SELECT NAME, ID FROM MEMBER WHERE ID = '100'  -- ID가 100인 ID, NAME 컬럼

SELECT ID AS 아이디, NAME FROM MEMBER WHERE ID = '100' -- ID가 100인 ID, NAME 컬럼

SELECT TEL FROM MEMBER WHERE NAME = 'PARK'

UPDATE MEMBER SET NAME = 'KIM' WHERE ID = '100'

UPDATE MEMBER SET NAME = 'YANG' WHERE ID = '200'

UPDATE MEMBER SET NAME = 'LEE' WHERE ID = '300'

SELECT * FROM MEMBER

UPDATE MEMBER SET TEL = '999', PW = '8888' WHERE ID = '100'

INSERT INTO MEMBER VALUES ('100','100','park','011')

INSERT INTO MEMBER VALUES ('200','200','park','011')

INSERT INTO MEMBER VALUES ('300','100','park','011')

SELECT * FROM MEMBER WHERE ID = '200' AND TEL = '011'

SELECT * FROM MEMBER WHERE ID = '200' OR TEL = '011'



SELECT * FROM MEMBER ORDER BY PW  -- 오름차순

SELECT * FROM MEMBER ORDER BY ID DESC -- 내림차순




SELECT * FROM PRODUCT ORDER BY PRICE DESC

SELECT * FROM PRODUCT ORDER BY COMPANY
--SELECT NAME, CONTENT, PRICE FROM PRODUCT ORDER BY COMPANY

SELECT * FROM PRODUCT WHERE ID = '100'
--SELECT NAME, PRICE FROM PRODUCT WHERE ID = '100'

SELECT * FROM PRODUCT WHERE PRICE = '5000'
--SELECT NAME, COMPANY FROM PRODUCT WHERE PRICE = '5000'

SELECT * FROM PRODUCT WHERE ID = '100' AND PRICE = '1000'
-- SELECT COMPANY, IMG FROM PRODUCT WHERE ID = '100' AND PRICE = '1000' 강사님 코드

SELECT * FROM PRODUCT WHERE COMPANY = 'c100'
--SELECT COMPANY, NAME FROM PRODUCT WHERE COMPANY = 'c100'

SELECT * FROM PRODUCT WHERE COMPANY = 'c100' OR COMPANY = 'c200'
-- SELECT NAME, PRICE FROM PRODUCT WHERE COMPANY = 'c100' OR COMPANY = 'c200' 강사님 코드

UPDATE PRODUCT SET CONTENT = '품절' WHERE PRICE = '5000'

UPDATE PRODUCT SET IMG = 'o.png', PRICE = '10000' WHERE ID = '100'

UPDATE PRODUCT SET IMG = 'o.png', PRICE = '10000' WHERE ID = '102'

-- UPDATE PRODUCT SET IMG = 'o.png', PRICE = '10000' WHERE ID = '100' OR ID = '102' 강사님 코드

UPDATE PRODUCT SET COMPANY = 'apple', NAME = 'appleshoes' WHERE ID = '101'

DELETE FROM PRODUCT WHERE NAME = 'shoes1' OR ID = '107'

DELETE FROM PRODUCT WHERE COMPANY = 'c100'

DELETE FROM PRODUCT

SELECT * FROM PRODUCT

DROP TABLE PRODUCT